version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4
        environment:
          PYTHONPATH: .
          SECRET_KEY: test_secret_key
          DJANGO_SETTINGS_MODULE: whichflix.settings.local
          DATABASE_URL: postgres://root:password@localhost/circle_test?sslmode=disable
          TMDB_API_KEY: test_tmdb_api_key
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            python ./whichflix/manage.py test
      - codecov/upload:
          file: ./foo.txt 
          token: 4ffe1df8-e575-4b16-a982-893576dd1b94
